# Use root/example as user/password credentials
networks:
  url-shortener-net:
      driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: url-shortener-app:v1
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - REDIS_HOST=cache
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - cache
    networks:
      - url-shortener-net
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - url-shortener-net

  cache:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
        - url-shortener-net
