# Use root/example as user/password credentials
networks:
  url-shortener-net:
      driver: bridge
volumes:
    mongoData:
        driver: local
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - url-shortener-net
    profiles:
      - production
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: url-shortener-app:v1
    restart: always
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - REDIS_HOST=cache
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    expose:
      - ${APP_PORT}
    depends_on:
      - mongo
      - cache
    networks:
      - url-shortener-net
    profiles:
      - production
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - url-shortener-net
    volumes:
      - mongoData:/data/db

  cache:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
        - url-shortener-net
