# Use root/example as user/password credentials
version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  cache:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
