version: "3.7"
networks:
    url-shortener-net:
        driver: overlay
        attachable: true
volumes:
    mongoData:
        driver: local

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
        replicas: 2
        restart_policy:
            condition: on-failure
    networks:
      - url-shortener-net
  app:
    image: url-shortener-app:v1
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - REDIS_HOST=cache
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mongo
      - cache
    secrets:
      - MONGO_USER
      - MONGO_PASSWORD
      - MONGO_DB
      - REDIS_PORT
    deploy:
        replicas: 2
        restart_policy:
            condition: on-failure
    networks:
      - url-shortener-net
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - url-shortener-net
    secrets:
      - MONGO_USER
      - MONGO_PASSWORD
    volumes:
      - mongoData:/data/db

  cache:
    image: redis:latest
    deploy:
        replicas: 1
        resources:
            limits:
                cpus: '0.5'
                memory: 512M
        restart_policy:
            condition: on-failure
    ports:
      - 6379:6379
    networks:
      - url-shortener-net
